import pandas as pd
import shutil
import os
# from .add_res import *
from datetime import timedelta
from docx import Document
# from .replace_the_dict import *
from multiprocessing import Pool
from colorama import Fore, init
PATH_result = os.getcwd() + r'/Auto_XC/MT_Script/report_result/'
PATH_TEMPLATE = os.getcwd() + r'/Auto_XC/MT_Script/report_template/'
init(autoreset=True)


def auto_edit_mt(book_path):
    """
    This function is used to automatically edit the MT file generated by AutoXC.
    """
    path_all = os.path.dirname(book_path) + "/"
    pt_doc = path_all + str(os.path.basename(book_path).split('.')[0]) + ".docx"
    bk1 = pd.read_excel(book_path, engine='openpyxl', sheet_name="超声总体信息", index_col=0,
                        header=None).T.reset_index(drop=True)  # 读取 excel 表, 获取总体信息
    bk2 = pd.read_excel(book_path, engine='openpyxl', sheet_name="超声原始记录")  # 读取 excel 表, 获取台账信息